on:
  push:
    branches: [ main ]

name: Precompile Binaries
jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
    
      - name: Set RUSTFLAGS for macOS
        if: (matrix.os == 'macOS-latest')
        run: |
          echo "RUSTFLAGS=-C link-arg=-undefined -C link-arg=dynamic_lookup" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=17.5" >> $GITHUB_ENV
          echo "IPHONEOS_DEPLOYMENT_TARGET=17.5" >> $GITHUB_ENV

      - name: Install Xcode Tools
        if: (matrix.os == 'macOS-latest')
        run: xcode-select --install || echo "Xcode tools already installed"

      - name: Set up Android SDK
        if: (matrix.os == 'ubuntu-latest')
        uses: android-actions/setup-android@v3

      - name: Precompile (with iOS)
        if: (matrix.os == 'macOS-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=SatoshiPortal/lwk-dart
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
      
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=SatoshiPortal/lwk-dart --android-sdk-location=/usr/local/lib/android/sdk --android-ndk-version=25.1.8937393 --android-min-sdk-version=23
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
